// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"
)

type Game struct {
	ID               string
	BaseTime         int32
	Increment        int32
	TournamentID     *string
	WhiteID          *int32
	BlackID          *int32
	GameLength       int16
	Result           int16
	CreatedAt        time.Time
	EndTimeLeftWhite *int32
	EndTimeLeftBlack *int32
	ResultReason     *string
	RatingW          int32
	RatingB          int32
	ChangeW          *int32
	ChangeB          *int32
}

type Move struct {
	ID           int32
	GameID       string
	MoveNumber   int32
	MoveNotation string
	Orig         string
	Dest         string
	MoveFen      string
	TimeLeft     *int32
}

type Session struct {
	ID        string
	UserID    int32
	CreatedAt time.Time
	ExpiresAt time.Time
}

type Tournament struct {
	ID        string
	Name      string
	StartTime time.Time
	Duration  int32
	BaseTime  int32
	Increment int32
	CreatedBy *int32
}

type TournamentPlayer struct {
	ID           int32
	PlayerID     int32
	TournamentID string
	Score        *int32
	Scores       []int16
	Streak       *int32
}

type User struct {
	ID         int32
	Email      string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Role       int16
	Username   *string
	AvatarUrl  *string
	GoogleID   string
	Rating     float64
	Rd         float64
	Volatility float64
}
