// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type Game struct {
	ID           string
	BaseTime     int32
	Increment    int32
	TournamentID *string
	WhiteID      *int32
	BlackID      *int32
	GameLength   int32
	Result       int32
	CreatedAt    time.Time
	TimeWhite    *int32
	TimeBlack    *int32
	Method       int32
	RatingW      int32
	RatingB      int32
	ChangeW      *int32
	ChangeB      *int32
	BerserkWhite bool
	BerserkBlack bool
}

type Move struct {
	ID           int32
	GameID       string
	MoveNumber   int32
	MoveNotation string
	Orig         string
	Dest         string
	MoveFen      string
	TimeLeft     *int32
}

type Session struct {
	ID        string
	UserID    int32
	CreatedAt time.Time
	ExpiresAt time.Time
}

type Tournament struct {
	ID             string
	Name           string
	StartTime      time.Time
	Duration       int32
	BaseTime       int32
	Increment      int32
	Status         int32
	BerserkAllowed bool
	CreatedBy      *int32
}

type TournamentPlayer struct {
	ID           int32
	PlayerID     int32
	TournamentID string
	Score        *int32
	Scores       []int32
	Streak       *int32
}

type User struct {
	ID         int32
	Email      string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Role       int32
	Username   *string
	AvatarUrl  *string
	GoogleID   string
	Rating     float64
	Rd         float64
	Volatility float64
}
