// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CsrfToken struct {
	SessionID string
	Token     string
	ExpiresAt time.Time
}

type Game struct {
	ID            int32
	WhitePlayerID pgtype.UUID
	BlackPlayerID pgtype.UUID
	Result        pgtype.Text
	CreatedAt     pgtype.Timestamp
	EndedAt       pgtype.Timestamp
}

type Move struct {
	ID           int32
	GameID       pgtype.Int4
	MoveNumber   int32
	PlayerID     pgtype.UUID
	MoveNotation string
	MoveFen      string
	CreatedAt    pgtype.Timestamp
}

type Session struct {
	ID        string
	UserID    uuid.UUID
	ExpiresAt time.Time
}

type User struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Username     string
	PasswordHash string
}
